[project]
name = "task-manager-api"
version = "0.1.0"
description = "A smart and minimal task manager API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "ruff>=0.11.7",
]
